image: python:3.7.0

pipelines:
  default:
    - step:
        name: Build and deploy
        script:
          - pip install ruamel.yaml python-docx pdfkit natsort --upgrade
          - bash bin/build.sh
