name: Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: sudo apt install libxrender1 wkhtmltopdf
      - name: Build
        run: bin/build.sh --create-opensong-package
      - name: Deploy songs to Emmet
        uses: joutvhu/ftp-transfer@v1
        with:
          host: ${{ vars.FTP_HOST }}
          username: ${{ vars.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          commands: |
            put dist/emmet.json ${{ vars.FTP_SUBDIR }}songs.json.new
            rename ${{ vars.FTP_SUBDIR }}songs.json ${{ vars.FTP_SUBDIR }}songs.json.${{ github.ref_name }}.bak
            rename ${{ vars.FTP_SUBDIR }}songs.json.new ${{ vars.FTP_SUBDIR }}songs.json
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
          files: |
            dist/opensong-enekek.zip
            dist/opensong-csomag.zip
            dist/emmet.json
            dist/emmanuel.dtx
            dist/emmet_offline.pdf
          fail_on_unmatched_files: true
